/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-10-08 at 00:29:17 UTC 
 * Modify at your own risk.
 */

package cz.muni.fi.sdipr.core.google.plus.model;

/**
 * Model definition for Acl.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google+ API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Acl extends com.google.api.client.json.GenericJson {

  /**
   * Description of the access granted, suitable for display.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String description;

  /**
   * The list of access entries.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PlusAclentryResource> items;

  /**
   * Identifies this resource as a collection of access controls. Value: "plus#acl".
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String kind;

  /**
   * Description of the access granted, suitable for display.
   * @return value or {@code null} for none
   */
  public String getDescription() {
    return description;
  }

  /**
   * Description of the access granted, suitable for display.
   * @param description description or {@code null} for none
   */
  public Acl setDescription(String description) {
    this.description = description;
    return this;
  }

  /**
   * The list of access entries.
   * @return value or {@code null} for none
   */
  public java.util.List<PlusAclentryResource> getItems() {
    return items;
  }

  /**
   * The list of access entries.
   * @param items items or {@code null} for none
   */
  public Acl setItems(java.util.List<PlusAclentryResource> items) {
    this.items = items;
    return this;
  }

  /**
   * Identifies this resource as a collection of access controls. Value: "plus#acl".
   * @return value or {@code null} for none
   */
  public String getKind() {
    return kind;
  }

  /**
   * Identifies this resource as a collection of access controls. Value: "plus#acl".
   * @param kind kind or {@code null} for none
   */
  public Acl setKind(String kind) {
    this.kind = kind;
    return this;
  }

  @Override
  public Acl set(String fieldName, Object value) {
    return (Acl) super.set(fieldName, value);
  }

  @Override
  public Acl clone() {
    return (Acl) super.clone();
  }

}
