/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-10-08 at 00:29:17 UTC 
 * Modify at your own risk.
 */

package cz.muni.fi.sdipr.core.google.plus.model;

/**
 * Model definition for Moment.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google+ API. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Moment extends com.google.api.client.json.GenericJson {

  /**
   * The moment ID.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String id;

  /**
   * Identifies this resource as a moment.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String kind;

  /**
   * The object generated by performing the action on the target. For example, a user writes a
   * review of a restaurant, the target is the restaurant and the result is the review.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ItemScope result;

  /**
   * Time stamp of when the action occurred in RFC3339 format.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime startDate;

  /**
   * The object on which the action was performed.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private ItemScope target;

  /**
   * The Google schema for the type of moment to write. For example,
   * http://schemas.google.com/AddActivity.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String type;

  /**
   * The moment ID.
   * @return value or {@code null} for none
   */
  public String getId() {
    return id;
  }

  /**
   * The moment ID.
   * @param id id or {@code null} for none
   */
  public Moment setId(String id) {
    this.id = id;
    return this;
  }

  /**
   * Identifies this resource as a moment.
   * @return value or {@code null} for none
   */
  public String getKind() {
    return kind;
  }

  /**
   * Identifies this resource as a moment.
   * @param kind kind or {@code null} for none
   */
  public Moment setKind(String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * The object generated by performing the action on the target. For example, a user writes a
   * review of a restaurant, the target is the restaurant and the result is the review.
   * @return value or {@code null} for none
   */
  public ItemScope getResult() {
    return result;
  }

  /**
   * The object generated by performing the action on the target. For example, a user writes a
   * review of a restaurant, the target is the restaurant and the result is the review.
   * @param result result or {@code null} for none
   */
  public Moment setResult(ItemScope result) {
    this.result = result;
    return this;
  }

  /**
   * Time stamp of when the action occurred in RFC3339 format.
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getStartDate() {
    return startDate;
  }

  /**
   * Time stamp of when the action occurred in RFC3339 format.
   * @param startDate startDate or {@code null} for none
   */
  public Moment setStartDate(com.google.api.client.util.DateTime startDate) {
    this.startDate = startDate;
    return this;
  }

  /**
   * The object on which the action was performed.
   * @return value or {@code null} for none
   */
  public ItemScope getTarget() {
    return target;
  }

  /**
   * The object on which the action was performed.
   * @param target target or {@code null} for none
   */
  public Moment setTarget(ItemScope target) {
    this.target = target;
    return this;
  }

  /**
   * The Google schema for the type of moment to write. For example,
   * http://schemas.google.com/AddActivity.
   * @return value or {@code null} for none
   */
  public String getType() {
    return type;
  }

  /**
   * The Google schema for the type of moment to write. For example,
   * http://schemas.google.com/AddActivity.
   * @param type type or {@code null} for none
   */
  public Moment setType(String type) {
    this.type = type;
    return this;
  }

  @Override
  public Moment set(String fieldName, Object value) {
    return (Moment) super.set(fieldName, value);
  }

  @Override
  public Moment clone() {
    return (Moment) super.clone();
  }

}
